### ISSUE TITLE
Overlapping sidebars

### ISSUE THREAD

**Issue by jaysonjaynes** [ucsf-web-services/ucsf_base#2]
When in the medium width screen size, sidebar-first is overlapped by sidebar-second. Example page: http://globalresearchhub.ucsf.edu/before-you-go
![screen shot 2014-08-28 at 10 31 37 am](https://cloud.githubusercontent.com/assets/2229010/4079843/7da6f2dc-2ed9-11e4-914e-b324d756006a.png)

**Comment by stopfstedt** [comment]
the second sidebar would have to clear left in that medium width screen size

``` css

.sidebar-second.col {
    clear: left;
}
```

**Comment by jaysonjaynes** [comment]
That's how I fixed it on the sub theme I worked on. I'll implement in the
base theme as well, unless you've done it...?

On Thu, Aug 28, 2014 at 10:49 AM, Stefan Topfstedt <notifications@github.com

**Comment by stopfstedt** [comment]
@jaysonjaynes if you're already on it, then please fork this repo, create branch and then send me a pull request.

**Comment by stopfstedt** [comment]
fixed by #4.
